String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>Leonardos!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same Lenardos touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'little red boy',
    '%4'                    : 'yellow little baby',
    '%8'                    : 'blue baldy',
    '%16'                   : 'grass child',
    '%32'                   : 'pinky winky',
    '%64'                   : 'ghost boy',
    '%128'                  : 'cute sky blue',
    '%256'                  : 'mean green bean',
    '%512'                  : 'party animal',
    '%1024'                 : 'love bug',
    '%2048'                 : 'dark night',
    '%4096'                 : 'german boy',
    '%8192'                 : 'earthy man',
    '%p0'                   : 'little red boy',
    '%p4'                   : 'yellow little baby',
    '%p8'                   : 'blue baldy',
    '%p16'                  : 'grass child',
    '%p32'                  : 'pinky winky',
    '%p64'                  : 'ghost boy',
    '%p128'                 : 'cute sky blue',
    '%p256'                 : 'mean green bean',
    '%p512'                 : 'party animal',
    '%p1024'                : 'love bug',
    '%p2048'                : 'dark night',
    '%p4096'                : 'german boy',
    '%p8192'                : 'earthy man'

	},

  "en": {
    "%game-intro"           : "Join the <strong>Leonardos!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same Lenardos touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048 Lenardos #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'little red boy',
    '%4'                    : 'yellow little baby',
    '%8'                    : 'blue baldy',
    '%16'                   : 'grass child',
    '%32'                   : 'pinky winky',
    '%64'                   : 'ghost boy',
    '%128'                  : 'cute sky blue',
    '%256'                  : 'mean green bean',
    '%512'                  : 'party animal',
    '%1024'                 : 'love bug',
    '%2048'                 : 'dark night',
    '%4096'                 : 'german boy',
    '%8192'                 : 'earthy man',
    '%p0'                   : 'little red boy',
    '%p4'                   : 'yellow little baby',
    '%p8'                   : 'blue baldy',
    '%p16'                  : 'grass child',
    '%p32'                  : 'pinky winky',
    '%p64'                  : 'ghost boy',
    '%p128'                 : 'cute sky blue',
    '%p256'                 : 'mean green bean',
    '%p512'                 : 'party animal',
    '%p1024'                : 'love bug',
    '%p2048'                : 'dark night',
    '%p4096'                : 'german boy',
    '%p8192'                : 'earthy man'
  }

});
